# Generated by Django 5.2.4 on 2025-08-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sobrenome', models.CharField(max_length=255)),
                ('data_nasc', models.DateField()),
                ('nacionalidade', models.CharField(max_length=50)),
                ('biografia', models.TextField()),
            ],
        ),
    ]
